/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaguaCell: typeof import('./src/components/bagua/BaguaCell.vue')['default']
    BaguaGrid: typeof import('./src/components/bagua/BaguaGrid.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatMessageBubble: typeof import('./src/components/chat/ChatMessageBubble.vue')['default']
    ChatSessionList: typeof import('./src/components/chat/ChatSessionList.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ErrorState: typeof import('./src/components/common/ErrorState.vue')['default']
    EvaluationPanel: typeof import('./src/components/admin/EvaluationPanel.vue')['default']
    FileCard: typeof import('./src/components/files/FileCard.vue')['default']
    FilePreview: typeof import('./src/components/files/FilePreview.vue')['default']
    FileUpload: typeof import('./src/components/files/FileUpload.vue')['default']
    FuxiLing: typeof import('./src/components/search/FuxiLing.vue')['default']
    KnowledgePanel: typeof import('./src/components/admin/KnowledgePanel.vue')['default']
    MiniBaguaCompass: typeof import('./src/components/bagua/MiniBaguaCompass.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAGTracePanel: typeof import('./src/components/chat/SAGTracePanel.vue')['default']
    SearchResult: typeof import('./src/components/search/SearchResult.vue')['default']
    ServicePlaceholder: typeof import('./src/components/common/ServicePlaceholder.vue')['default']
    ShortcutHelp: typeof import('./src/components/common/ShortcutHelp.vue')['default']
    StatusIndicator: typeof import('./src/components/bagua/StatusIndicator.vue')['default']
    StreamingIndicator: typeof import('./src/components/chat/StreamingIndicator.vue')['default']
    SystemStatus: typeof import('./src/components/admin/SystemStatus.vue')['default']
    TajiiIcon: typeof import('./src/components/bagua/TajiiIcon.vue')['default']
    UploadZone: typeof import('./src/components/files/UploadZone.vue')['default']
    UserPanel: typeof import('./src/components/admin/UserPanel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
